### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Madji** [oscarcappa/HomeKeeper#1]
Hello why it does not work. for example, when you restart a message comes in. and what about plugins

**Comment by DrG33k** [comment]
Hello, did you send the password to the bot?
If not it ignore each command, after send the password try to send "ping"

**Comment by Madji** [comment]
Yes I sent the password to the bot that was defined when installing the,but the answer is nothing, and after the bot just mariagirl on that either

**Comment by Madji** [comment]
Yes, I'm sorry. despite the fact that jq was standing from the repository of ubuntu 14.04 64. to download jq from github and compile. Only after that it worked !

**Comment by DrG33k** [comment]
Good to know, enjoy it!
